language: c

git:
  depth: 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8-multilib
      - linux-libc-dev
      - g++-4.8
      - texlive
      - texinfo
      - valgrind
  coverity_scan:
    project:
      name: $TRAVIS_REPO_SLUG
      description: MATLAB MAT File I/O Library
    notification_email: $COVERITY_SCAN_EMAIL
    build_command: make
    branch_pattern: coverity_scan

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "C2T0NCiqo98RZXaBTqSWpxcpKhAryOD9VcZ02keuyOPCeNpaLKeo36R/8iAhHWvQddU3V9x0H8EHGN4QY78I1kH3OTwTsGueyRTjKvBsrWlR88pO0CJ33MXz9IvpVE32zACKt2Ltj2GBIUzl0Nm6uwjJXW59pL/86X9ShHK/+hs8Trqu3Zm8MiWg0z79xZzHo+9m7RXW0i5jwxBfIbW15GIMc1TMZC31eHBDjQRCTL89IZzJXVf1ZCd+OsUpvuOVneAl9ihvqyZ3fkK/8n7iVr3TzJDIpj4I3AgVSdg6D0vNsW5HE/czZKTHs6yVI/ImcpPnyApd85MKxjkyppDi3WTBvWn4MkPDMxj1ZJzDQ+0tGIcfaQn9uXiwZCIIezodFK5aY8/OoK9/cVRfjHjZrXkv+hfH0Xys9DrlhSKpeusU0hAS2yoz10g+aN/Sz4fGeRlGrvU0HIncFdXLsD30v7LDTZn4dBIH7C+xE6pbcQ7Y3bGEC3CyR0UbFCbjY20JPMa0k7FBmLRpBUHn9mxJ/eJSnWH/ZI4YRWyJd5fAQvUPvY+5oP+IaEo0oZgSelEUnEssmySFFrVN4YC1GJb63AT7tLPnhgghmzSZUMG/l7Zj0++TEQv+OhtVg8E57iSV0l7WXXwapCyjbFHvjPEwvgZ3plc9XOo+HqYxeHtkx40="
    # COVERITY_SCAN_EMAIL
    - secure: "Qux4CPWkAXdpWPbUwqKTtimTU/xKC2oLtqzH5oMYuTUqyAX9D6XAEx+lq5ADNk5UAQuq4kCWYxPyNOu85vZPV/9INBZ9sSJ+Y5cbQLpJ6nqY7nQHuL5WoIHDtyabgo3mKlsY4mkpM0qcHgHib98/j7vG573pBfp4ihcUu5eKUNxlP07nUILeBPpuJz5GWoCzikU9M0tgjwmydWoa+dJ726HPoPjsu2VY1RFov63u+BWX/c3FUTWyleGVIsQbQeQUcIjMMtHyv0r3wqdsryk88m1rEpDrAy60fki71lcfGuxhzgkSMLezFu2Qj8EqtUrC+Xh4/VIFdn3XbR527OrTQrkJYDelZvEQSoEd3NgiWu5A0R+Zr68YJLjPHoW4TJFj0AG7Nek9bBr27CJOMjAzBVp8FMcVl3/6ApfJb0R89vslPA0J+p/UJdmjhuriiigojMwJQwESpRLtp+oietfr2UtQUeMc9AqCZf4jRzNK4ooEC75Z9MM2FFiuDLhAyYsCwwHrHilXHCCStdjs1jk7YV1+AyU5HIokAYPXjWwxT5BWSIc5wfnIj4lGdMhzJien8/qjyU6kQPiikorKTgd2eD6KzQULuccPudnN9lK6eT+DY4LZ3rfSMGFkMA72w0nmEK4sTGuT8zMC9KS0hgat5b8mzSJ3xhaXig3gQXkrYZk="
    # BBPASS
    - secure: "URJPdQ3u2iqPjyurd9ooGxlAMYBbVaQILl1x0VlL830gxNHcPy4sKbs6CgPnZymJ3xV6afQFOKZW0b2Yg6Vi/alcun1FG/L2YO+otClQJjhQAhl2ZxzicEzoTqQ2UwoA+IbCAUWBThPq8lg6AsYu17rpIdeUji6yV1UkD4ipz3Md0vOqt1tY90uKz9Q8PVIpkrnYcZL3SB1xXc1i4Msijo2vB/bQAYl+v5yXgMRLDOstrRxe4U7T9GZoRcQdyrzm0PK0nKCpy7JM3g4agvgvmfIGjwtCCweof3RoMZ/8DLpzJ8E/nt7jE97fGqMTNrfX4Of9+NrexivWWv44U2zXOaTI9tGodWx5BfGrbSf5y8Y+RiW2DDmyCdczm7cpCzTCiS9RQcIWXphoiAdiYcDxwv83K9N/t5NV36Q3oFB05Qu19DFB9vy8AsgKx5NVTN9WXoFo1fp/3dguJr/R7mrTY9M9llTxEwoaifyxpEUMWJws3/ZZpBZf+HfhO8k98Shw/CEIqw492Y5DVqVkX+ZtIKq02ZVw5cdnHXSEt5ZUfaZqADvMFiTHuFL1f/P5Sf8ZFTxmYbNtrQLzq8aj8r3QSEc0Kcp+LIH4oMhgVBfYUXdDJJNzJMzVmcr8PigUhl0mSR+fzMyYLQ53hRcJlf38AH9CfKzn6WDoF6jkJZYN4Aw="

matrix:
  include:
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.12.0
        - MAX_RANK=3
    - os: linux
      arch: arm64
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.12.0
        - MAX_RANK=3
    - os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      dist: xenial
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.12.0
        - MAX_RANK=3
    - os: linux
      arch: s390x
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.12.0
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.10.7
        - MAX_RANK=3
    - os: linux
      arch: arm64
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.10.7
        - MAX_RANK=3
    - os: linux
      arch: arm64-graviton2
      group: edge
      virt: lxd
      dist: xenial
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=$TRAVIS_BUILD_DIR/zlib
        - HDF5_VERSION=1.10.7
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8.21
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8.21
        - MAX_RANK=1
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=no
        - HDF5_VERSION=1.8.21
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=no
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8.21
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=no
        - WITH_ZLIB=no
        - HDF5_VERSION=1.8.21
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=no
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8.21
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=no
        - ENABLE_MAT73=yes
        - WITH_ZLIB=no
        - HDF5_VERSION=1.8.21
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=no
        - ENABLE_MAT73=no
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8.21
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - ENABLE_EXTENDED_SPARSE=no
        - ENABLE_MAT73=no
        - WITH_ZLIB=no
        - HDF5_VERSION=1.8.21
        - MAX_RANK=3
    - os: linux
      compiler: gcc-4.8
      env:
        - USE_CMAKE=yes
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.10.7
    - os: linux
      compiler: gcc-4.8
      env:
        - USE_CMAKE=yes
        - USE_CONAN=yes
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
    - os: linux
      compiler: clang
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8.21
        - MAX_RANK=3
    - os: osx
      compiler: clang
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - HDF5_VERSION=1.8.21
        - MAX_RANK=3
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - MAX_RANK=3
        - HDF5_VERSION=foo
        - HOMEBREW_DEPLOY=yes
        - HOMEBREW_NO_ANALYTICS=1

before_install: ./.ci/travis_before_install.sh

install: ./.ci/travis_install.sh

before_script: ./.ci/travis_before_script.sh

script: ./.ci/travis_script.sh

after_success: ./.ci/travis_after_success.sh

notifications:
  email: false

sudo: required
